#server.port=18080

base.file.path=${BASE_FILE_PATH}
#base.file.path=/home/firstdev/mydata/fh-files
spring.application.name=file-handler

# parametros para controlar 
# la subida de archivos

# determines whether multipart has to be enabled or not
spring.servlet.multipart.enabled=true

# specifies the maximum size of the file allowed for uploading.
spring.servlet.multipart.max-file-size=10KB

# specifies the maximum size allowed for multipart/form-data requests.
spring.servlet.multipart.max-request-size=10KB

# database config docker
#spring.datasource.url=jdbc:postgresql://localhost:5436/${DBNAME1}
#spring.datasource.username=${DBUSER1}
#spring.datasource.password=${DBPASS1}

# databas config aws
spring.datasource.url=jdbc:postgresql://${DBHOST2}:5432/${DBNAME2}
spring.datasource.username=${DBUSER2}
spring.datasource.password=${DBPASS2}

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
